### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dbaelde** [Clematrics/penGui#2]
When building 8b934bbba159be501ff0c925f88cdf6f2adcb405, I get several errors of this kind:
```
error[E0010]: allocations are not allowed in statics
  --> src/core/draw_commands.rs:61:19
   |
61 |     index_buffer: vec![],
   |                   ^^^^^^ allocation not allowed in statics
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Since this could be due to different versions of the Rust compiler, here is the version I use:
```
dbaelde@ger penGui $ rustc --version
rustc 1.43.0
```

**Comment by Clematrics** [comment]
The last commit was compiled with the version 1.47.0.
I just tested with the latest version (1.48.0), it is also working.
We indeed need to check the version of the compiler and abort the build when a version requirement isn't met.
You can still upgrade the rust toolchain either with your package manager or using `rustup update stable` if rust was installed using `rustup`.
